//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluationWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bien()
        {
            this.Liaison = new HashSet<Liaison>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Valeur { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual Bien Bien1 { get; set; }
        public virtual Bien Bien2 { get; set; }
        public virtual Bien Bien11 { get; set; }
        public virtual Bien Bien3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liaison> Liaison { get; set; }
    }
}
