//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluationWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liaison
    {
        public int IdBien { get; set; }
        public int IdProprietaire { get; set; }
        public int Unique { get; set; }
    
        public virtual Bien Bien { get; set; }
        public virtual Proprietaire Proprietaire { get; set; }
        public virtual Proprietaire Proprietaire1 { get; set; }
    }
}
